[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "scalar-fastapi>=1.4.3",
]

[dependency-groups]
dev = [
    "lefthook>=2.0.15",
    "ruff>=0.14.11",
    "ty>=0.0.13",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.ruff.lint]
select = ["I"]